controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes de notre application

# Controller : HomeController

# Appelle la page d'accueil
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST
# front-office

app_membre:
    path: /membre
    controller: App\Controller\MembreController::dashboard
    methods: GET

app_details_membre:
    path: /membre/mon-compte/details-mon-compte
    controller: App\Controller\MembreController::detailsCompte
    methods: GET

app_modifier_mon_compte:
    path: /membre/mon-compte/modifier-mon-compte
    controller: App\Controller\MembreController::modifierCompte
    methods: GET|POST

app_supprimer_compte:
    path: /membre/mon-compte/supprimer-mon-compte/{id}
    controller: App\Controller\MembreController::supprimerCompte
    methods: GET
# Pages statiques

app_legal:
    path: /mentions
    controller: App\Controller\StaticController::mentionsLegales
    methods: GET

app_faq:
    path: /faq
    controller: App\Controller\StaticController::faq
    methods: GET|POST

app_cookies:
    path: /confidentialite
    controller: App\Controller\StaticController::politiqueCookies
    methods: GET

app_about:
    path: /qui-sommes-nous
    controller: App\Controller\StaticController::about
    methods: GET

app_cgv:
    path: /conditions-generales-ventes
    controller: App\Controller\StaticController::cgv
    methods: GET

app_utilisation:
    path: /conditions-utilisations
    controller: App\Controller\StaticController::utilisation
    methods: GET


#---------------------------------------------------

app_champagne:
    path: /champagnes
    controller: App\Controller\ChampagneController::champagne
    methods: GET

app_detail_champagne:
    path: /champagnes/detail/{champagne}
    controller: App\Controller\ChampagneController::detailsChampagne
    methods: GET|POST

app_modifier_champagne:
    path: /champagnes/modifier/{champagne}
    controller: App\Controller\ChampagneController::modifierChampagne
    methods: GET|POST

app_supprimer_champagne:
    path: /champagnes/supprimer/{champagne}
    controller: App\Controller\ChampagneController::supprimerChampagne
    methods: GET|POST

app_mon_panier:
    path: /mon-panier
    controller: App\Controller\CartController::panier
    methods: GET|Post

app_ajout_panier:
    path: /ajouter/mon-panier/{id}
    controller: App\Controller\CartController::add
    methods: GET|POST

app_supprimer_article_panier:
    path: /supprimer/mon-panier/{id}
    controller: App\Controller\CartController::decrease
    methods: GET|POST

app_supprimer_ligne_panier:
    path: /supprimer/ligne-panier/{id}
    controller: App\Controller\CartController::deleteCartById
    methods: GET|POST

app_supprimer_panier:
    path: /supprimer/mon-panier
    controller: App\Controller\CartController::delete
    methods: GET|POST

app_panier:
    path: /panier/details
    controller: App\Controller\PanierController::cartDetails
    methods: GET|POST

app_ajouter_au_panier:
    path: /panier
    controller: App\Controller\PanierController::panier
    methods: POST


app_commande:
    path: /commande
    controller: App\Controller\CommandeController::commande
    methods: GET|POST

app_preparation_commande:
    path: /commande/preparation
    controller: App\Controller\CommandeController::preparationCommande
    methods: GET|POST

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET,POST]

app_logout:
    path: /logout
    methods: GET

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

# app_email_conf_sent:
#     path: /signup/confirmation
#     controller: App\Controller\RegistrationController::postSignUp


# Routes Back Office Admin

app_admin:
    path: /admin
    controller: App\Controller\AdminController::dashboard
    methods: GET|POST

app_admin_cepage:
    path: /admin/cepage
    controller: App\Controller\AdminController::addCepage
    methods: GET|POST

app_admin_typeProduit:
    path: /admin/typeProduit
    controller: App\Controller\AdminController::addType
    methods: GET|POST

app_admin_transporter:
    path: /admin/transporter
    controller: App\Controller\AdminController::addTransporter
    methods: GET|POST

app_membre_management:
    path: /admin/membre-management
    controller: App\Controller\AdminController::membreManagement
    methods: GET|POST

app_modifier_membre:
    path: /admin/membre-modifier/{member}
    controller: App\Controller\AdminController::modifierMembre
    methods: GET|POST

app_supprimer_membre:
    path: /admin/supprimer-membre/{member}
    controller: App\Controller\AdminController::supprimerMembre
    methods: GET|POST

app_contact:
    path: /contact
    controller: App\Controller\ContactController::contact
    methods: GET|POST




# Stripe

app_stripe:
  path: /stripe/{reference}
  controller: App\Controller\StripeController::index
  methods: GET|POST


app_stripe_charge:
  path: /stripe/create-charge
  controller: App\Controller\StripeController::createCharge
  methods: POST


app_stripe_success:
  path: /order/confirmation/{reference}
  controller: App\Controller\StripeController::stripeSuccess
  methods: GET|POST


app_stripe_fail:
  path: /payment/failure/{reference}
  controller: App\Controller\StripeController::stripeError
  methods: GET|POST