controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Routes de notre application

# Controller : HomeController

# Appelle la page d'accueil
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

# Pages statiques

app_legal:
    path: /mentions
    controller: App\Controller\StaticController::mentionsLegales
    methods: GET


app_cookies:
    path: /confidentialite
    controller: App\Controller\StaticController::politiqueCookies
    methods: GET

app_about:
    path: /qui-sommes-nous
    controller: App\Controller\StaticController::about
    methods: GET

app_cgv:
    path: /conditions-generales-ventes
    controller: App\Controller\StaticController::cgv
    methods: GET

app_utilisation:
    path: /conditions-utilisations
    controller: App\Controller\StaticController::utilisation
    methods: GET


#---------------------------------------------------

app_champagne:
    path: /champagnes
    controller: App\Controller\ChampagneController::champagne
    methods: GET


app_connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::connexion
    methods: GET|POST


app_panier:
    path: /monpanier
    controller: App\Controller\PanierController::index
    methods: GET|POST

app_inscription:
    path: /inscription
    controller: App\Controller\InscriptionController::inscription
    methods: GET|POST

app_commande:
    path: /commande
    controller: App\Controller\CommandeController::commande
    methods: GET|POST